# Generated by Django 5.1.2 on 2024-12-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='avartar',
            field=models.ImageField(null=True, upload_to='avartar/'),
        ),
    ]
