# Generated by Django 5.1.2 on 2024-12-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_avartar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='avartar',
            field=models.ImageField(null=True, upload_to='avatar/'),
        ),
    ]
