# Generated by Django 5.1.2 on 2024-12-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useraccount_avartar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='avartar',
            new_name='avatar',
        ),
    ]
